name: "infer-mobilenetv2"
platform: "onnxruntime_onnx"
max_batch_size: 16
input [
  {
    name: "input",
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 3, 224, 224 ]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ 1000 ]
    label_filename: "imagenet_labels.txt"
  }
]
instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]
dynamic_batching { }
version_policy: { all { }}